# Variable: POST.SOGoMailListViewColumnsOrder
# Value: Flagged,Attachment,Priority,From,Subject,Unread,Date,Size
# Impact: 4 | Tags: xss, csrf, id, rfe
# Description: Detects JavaScript object properties and methods | Tags: xss, csrf, id, rfe | ID 17

any:/mail/sogo_mail_domains_edit.php:POST.SOGoMailListViewColumnsOrder
## Only allow clients
#user:/mail/sogo_mail_domains_edit.php:POST.SOGoMailListViewColumnsOrder
## Only allow admins
#admin:/mail/sogo_mail_domains_edit.php:POST.SOGoMailListViewColumnsOrder

# --------------------------------------------------------------------------- #

# Variable: POST.SOGoSubscriptionFolderFormat
# Value: %{FolderName} (%{UserName} &lt;%{Email}&gt;)
# Impact: 19 | Tags: xss, csrf, id, rfe, lfi
# Description: Detects self-executing JavaScript functions | Tags: xss, csrf | ID 8
# Description: Detects code injection attempts 1/3 | Tags: id, rfe, lfi | ID 58
# Description: Detects unknown attack vectors based on PHPIDS Centrifuge detection | Tags: xss, csrf, id, rfe, lfi | ID 67

any:/mail/sogo_mail_domains_edit.php:POST.SOGoSubscriptionFolderFormat
## Only allow clients
#user:/mail/sogo_mail_domains_edit.php:POST.SOGoSubscriptionFolderFormat
## Only allow admins
#admin:/mail/sogo_mail_domains_edit.php:POST.SOGoSubscriptionFolderFormat

# --------------------------------------------------------------------------- #

# Variable: POST.SOGoCustomXML
# Value: &lt;key&gt;ValidKeyName&lt;/key&gt;&lt;string>I am valid but i will never be used by SOGo&lt;/string&gt;
# Impact: 33 | Tags: xss, csrf, id, rfe, sqli, lfi
# Description: Finds html breaking injections including whitespace attacks | Tags: xss, csrf | ID 1
# Description: Finds attribute breaking injections including whitespace attacks | Tags: xss, csrf | ID 2
# Description: Detects self-executing JavaScript functions | Tags: xss, csrf | ID 8
# Description: Detects JavaScript language constructs | Tags: xss, csrf, id, rfe | ID 20
# Description: Detects JavaScript cookie stealing and redirection attempts | Tags: xss, csrf | ID 26
# Description: Detects MySQL comment-/space-obfuscated injections and backtick termination | Tags: sqli, id | ID 57
# Description: Detects unknown attack vectors based on PHPIDS Centrifuge detection | Tags: xss, csrf, id, rfe, lfi | ID 67

any:/mail/sogo_mail_domains_edit.php:POST.SOGoCustomXML
## Only allow clients
#user:/mail/sogo_mail_domains_edit.php:POST.SOGoCustomXML
## Only allow admins
#admin:/mail/sogo_mail_domains_edit.php:POST.SOGoCustomXML